docs: highlight announcement bar feature
quarto-dev/quarto-web pull request #1104
Opened 2024-05-23 20:08 UTC by mcanouil

This pull request adds a new highlight about the new feature: the website announcement bar. With this feature, users can add a customizable announcement bar to their websites, allowing them to highlight important information, alerts, promotions, or updates. The announcement bar can be positioned above or below the navbar and can be dismissed by the user. Users can also choose from a variety of Bootstrap icons and format the content using markdown.

2024-05-23 21:42 UTC, cderv commented
/deploy-preview

2024-05-23 21:44 UTC, cderv commented
Isn't it 1.5 feature ? If so, I think we should do the PR on prelease branch for the prerelease website. 

@cwickham do we want to still do highlights for this release or start using prerelease branch ? I would think the latter.

2024-05-23 22:04 UTC, cwickham commented
Yeah, I think we want highlights to live on the prerelease site.

For this PR:
* Target the `prerelease` branch
* Move `docs/prerelease/1.5/website-announcement.qmd` to a permanent home. Perhaps `docs/websites/_website-announcement.md` and then put it in `docs/websites/website-tools.qmd` as an `{{< include >}}`?
* Link directly to the permanent home from `_highlights.yml`

2024-06-20 18:21 UTC, mcanouil commented
Refactored to include the announcement in "website tools".

2024-06-21 09:23 UTC, cderv commented
/deploy-preview

2024-06-21 09:43 UTC, mcanouil commented
- https://deploy-preview-1104.quarto.org/docs/websites/website-tools.html#announcement-bar

Maybe decrease the width of the screenshot?

2024-06-21 12:00 UTC, cderv commented
> Maybe decrease the width of the screenshot?

Or the reduce the height while keep the width ?

2024-06-21 12:03 UTC, mcanouil commented
I meant keep the ratio but make it smaller^^

2024-06-21 12:32 UTC, cderv commented
> I meant keep the ratio but make it smaller^^

Yes I got it. I am thinking not keeping the ratio, just reduce the height and keep the width ^^

2024-06-21 12:36 UTC, mcanouil commented
The, I'll crop the screenshot ;)

2024-06-21 14:25 UTC, cderv commented
/deploy-preview

2024-06-24 16:39 UTC, cwickham requested changes
Looking good! Just a few suggestions in the comments.

2024-06-24 16:39 UTC, cwickham commented on docs/books/book-output.qmd
> +-   [Announcement Bar](/docs/websites/website-tools.qmd#announcement-bar)
I doesn't currently work for Books. I've opened an [issue](https://github.com/quarto-dev/quarto-cli/issues/10114). Omit this for now.

2024-06-24 16:39 UTC, cwickham commented on docs/prerelease/1.5/_highlights.qmd
> +-   [Website Announcement Bar](/docs/websites/website-tools.qmd#announcement-bar)---Add an announcement bar to your website.
This looks good. But can you move it up to be under "Website Drafts"?

2024-06-24 16:39 UTC, cwickham commented on docs/websites/website-tools.qmd
> +The announcement bar can be positioned to fit seamlessly within your site's layout (*e.g.*, `below-navbar` or `above-navbar`), ensuring the message is both impactful and integrated.
Some wording/ordering edits to make this a bit more concise:
```suggestion
Add an announcement to display a prominent, customizable bar at the top of your website that grabs visitors' attention.
It's perfect for highlighting important information, such as alerts, promotions, or updates.
You can set an icon, make it dismissable, and even include formatted content like bold text.
The announcement bar can be positioned to fit seamlessly within your site's layout (*e.g.*, `below-navbar` or `above-navbar`), ensuring the message is both impactful and integrated.
```

2024-06-24 17:01 UTC, mcanouil commented on docs/books/book-output.qmd
> +-   [Announcement Bar](/docs/websites/website-tools.qmd#announcement-bar)
I thought it would.
Nice catch!

2024-06-24 20:03 UTC, mcanouil commented on docs/books/book-output.qmd
> +-   [Announcement Bar](/docs/websites/website-tools.qmd#announcement-bar)
```suggestion
```

2024-06-24 20:03 UTC, mcanouil commented on docs/prerelease/1.5/_highlights.qmd
> +-   [Website Announcement Bar](/docs/websites/website-tools.qmd#announcement-bar)---Add an announcement bar to your website.
done

2024-06-24 20:36 UTC, cwickham commented
/deploy-preview

2024-06-26 18:24 UTC, cwickham approved these changes

2024-06-26 18:27 UTC, merged