Add speakernotes to the extensions list
quarto-dev/quarto-web pull request #1355
Opened 2024-09-26 13:33 UTC by pagiraud

2024-09-26 16:32 UTC, cscheid requested changes

2024-09-26 16:32 UTC, cscheid commented on docs/extensions/listings/shortcodes-and-filters.yml
> + - name: speakernotes
You need to indent this correctly. Note the stray space before `-`

2024-09-26 16:52 UTC, pagiraud commented on docs/extensions/listings/shortcodes-and-filters.yml
> + - name: speakernotes
Ah sorry, I didn’t notice that. That should be good now.

2024-09-26 19:56 UTC, merged

2024-09-27 08:55 UTC, cderv commented
Solved ! 

Sorry - I did some changed to main that I forgot to push also on pre-release so it lead to conflict! 

All good now.