pre-release docs for publishing to Posit Cloud
quarto-dev/quarto-web pull request #823
Opened 2023-09-07 20:04 UTC by mslynch

Once 1.4 is released, this should move to `docs/publishing/posit-cloud.qmd`.

2023-09-07 20:04 UTC, mslynch commented on docs/publishing/posit-cloud.qmd
This is based heavily on `docs/publishing/rstudio-connect.qmd`.

2023-09-08 10:52 UTC, cderv commented
/deploy-preview

2023-11-30 01:14 UTC, cwickham requested changes
This looks great, and I'd like to get it up into our 1.4 highlights page now. 
I've made a few specific comments on `docs/publishing/cloud.qmd`. I'll prep it's move into the highlights section, so we can get it merged once you address them.

2023-11-30 01:14 UTC, cwickham commented on docs/publishing/posit-cloud.qmd
> +    ![](images/gh-action-posit-cloud-secret.png){.border}
Please add alt text

2023-12-01 21:41 UTC, cwickham commented
/deploy-preview

2023-12-03 20:50 UTC, merged